applications/security/urls.py
from django.urls import path
from applications.core.views.historialclinico import HistorialClinicoCreateView, HistorialClinicoDeleteView, HistorialClinicoDetailView, HistorialClinicoListView, HistorialClinicoUpdateView
from applications.security.views.ajax import get_modules_by_menus, get_permissions_by_module
from applications.security.views.auth import signin, signout
from applications.security.views.menu import MenuCreateView, MenuDeleteView, MenuListView, MenuUpdateView
from applications.security.views.module import ModuleCreateView, ModuleDeleteView, ModuleListView, ModuleUpdateView
from applications.security.views.user import UserCreateView, UserDeleteView, UserListView, UserUpdateView
from applications.security.views.group import GroupCreateView, GroupDeleteView, GroupListView, GroupUpdateView
from applications.security.views.groupmodulepermission import (
    GroupModulePermissionCreateView, GroupModulePermissionDeleteView,
    GroupModulePermissionListView, GroupModulePermissionUpdateView
)

app_name='security' # define un espacio de nombre para la aplicacion
urlpatterns = [

# rutas de modulos
  path('module_list/',ModuleListView.as_view() ,name="module_list"),
  path('module_create/', ModuleCreateView.as_view(),name="module_create"),
  path('module_update/<int:pk>/', ModuleUpdateView.as_view(),name='module_update'),
  path('module_delete/<int:pk>/', ModuleDeleteView.as_view(),name='module_delete'),

# rutas de menus
  path('menu_list/',MenuListView.as_view() ,name="menu_list"),
  path('menu_create/', MenuCreateView.as_view(),name="menu_create"),
  path('menu_update/<int:pk>/', MenuUpdateView.as_view(),name='menu_update'),
  path('menu_delete/<int:pk>/', MenuDeleteView.as_view(),name='menu_delete'),

# rutas de usuarios
  path('user_list/', UserListView.as_view(), name='user_list'),
  path('user_create/', UserCreateView.as_view(), name='user_create'),
  path('user_update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
  path('user_delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),

# rutas de grupos
  path('group_list/', GroupListView.as_view(), name='group_list'),
  path('group_create/', GroupCreateView.as_view(), name='group_create'),
  path('group_update/<int:pk>/', GroupUpdateView.as_view(), name='group_update'),
  path('group_delete/<int:pk>/', GroupDeleteView.as_view(), name='group_delete'),

# rutas de groupmodulepermission
  path('groupmodulepermission_list/', GroupModulePermissionListView.as_view(), name='groupmodulepermission_list'),
  path('groupmodulepermission_create/', GroupModulePermissionCreateView.as_view(), name='groupmodulepermission_create'),
  path('groupmodulepermission_update/<int:pk>/', GroupModulePermissionUpdateView.as_view(), name='groupmodulepermission_update'),
  path('groupmodulepermission_delete/<int:pk>/', GroupModulePermissionDeleteView.as_view(), name='groupmodulepermission_delete'),

  # rutas de autenticacion
  path('logout/', signout, name='signout'),
  path('signin/', signin, name='signin'),
  #path('signup/', signup, name='signup'),
  path('get_modules_by_menus/', get_modules_by_menus, name='get_modules_by_menus'),
  path('get_permissions_by_module/', get_permissions_by_module, name='get_permissions_by_module'),
  
  
]

proy_clinico/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from applications.security.views.home import ModuloTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', ModuloTemplateView.as_view(), name='home'),
    path('security/', include('applications.security.urls', namespace='security')),
    path('core/', include('applications.core.urls', namespace='core')),
    path('doctor/', include('applications.doctor.urls', namespace='doctor')),
    path("__reload__/", include("django_browser_reload.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/security/views.py
# from django.shortcuts import render

# def home(request): 
#     return render(request, 'home.html')

applications/security/views/ajax.py
from django.http import JsonResponse
from applications.security.models import Module, Menu
from django.contrib.auth.models import Permission

def get_modules_by_menus(request):
    menu_ids = request.GET.get('menus', '')
    menu_ids = menu_ids.split(',') if menu_ids else []
    modules = Module.objects.filter(menu__id__in=menu_ids).distinct()
    modules_data = [{'id': m.id, 'name': m.name} for m in modules]
    return JsonResponse({'modules': modules_data})

def get_permissions_by_module(request):
    module_id = request.GET.get('module_id')
    if module_id:
        permissions = Permission.objects.filter(module__id=module_id)
        permissions_data = [{'id': p.id, 'name': p.name} for p in permissions]
    else:
        permissions_data = []
    return JsonResponse({'permissions': permissions_data})

applications/security/views/group.py
from django.contrib import messages
from django.urls import reverse_lazy
from applications.security.components.mixin_crud import (
    CreateViewMixin, DeleteViewMixin, ListViewMixin, PermissionMixin, UpdateViewMixin
)
from django.contrib.auth.models import Group
from applications.security.forms.group import GroupForm
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.db.models import Q

class GroupListView(PermissionMixin, ListViewMixin, ListView):
    template_name = 'security/groups/list.html'
    model = Group
    context_object_name = 'groups'
    permission_required = 'auth.view_group'

    def get_queryset(self):
        q1 = self.request.GET.get('q')
        queryset = self.model.objects.all().order_by('id')
        if q1:
            queryset = queryset.filter(name__icontains=q1)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('security:group_create')
        # Si usas permisos en contexto, mantenlo, sino eliminar print
        print(context.get('permissions'))
        return context


class GroupCreateView(PermissionMixin, CreateViewMixin, CreateView):
    model = Group
    template_name = 'security/groups/form.html'
    form_class = GroupForm
    success_url = reverse_lazy('security:group_list')
    permission_required = 'auth.add_group'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['grabar'] = 'Grabar Grupo'
        context['back_url'] = self.success_url
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        group = self.object
        messages.success(self.request, f"Éxito al crear el grupo {group.name}.")
        return response


class GroupUpdateView(PermissionMixin, UpdateViewMixin, UpdateView):
    model = Group
    template_name = 'security/groups/form.html'
    form_class = GroupForm
    success_url = reverse_lazy('security:group_list')
    permission_required = 'auth.change_group'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['grabar'] = 'Actualizar Grupo'
        context['back_url'] = self.success_url
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        group = self.object
        messages.success(self.request, f"Éxito al actualizar el grupo {group.name}.")
        return response


class GroupDeleteView(PermissionMixin, DeleteViewMixin, DeleteView):
    model = Group
    template_name = 'core/delete.html'
    success_url = reverse_lazy('security:group_list')
    permission_required = 'auth.delete_group'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['grabar'] = 'Eliminar Grupo'
        context['description'] = f"¿Desea eliminar el grupo: {self.object.name}?"
        context['back_url'] = self.success_url
        return context

    def form_valid(self, form):
        group_name = self.object.name
        response = super().form_valid(form)
        messages.success(self.request, f"Éxito al eliminar el grupo {group_name}.")
        return response

applications/security/views/groupmodulepermission.py
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.db.models import Q
from applications.security.models import GroupModulePermission
from applications.security.forms.groupmodulepermission import GroupModulePermissionForm
from applications.security.components.mixin_crud import PermissionMixin, CreateViewMixin, UpdateViewMixin, DeleteViewMixin, ListViewMixin

class GroupModulePermissionListView(PermissionMixin, ListViewMixin, ListView):
    model = GroupModulePermission
    template_name = 'security/groupmodulepermission/list.html'
    context_object_name = 'groupmodulepermissions'
    permission_required = 'view_groupmodulepermission'

    def get_queryset(self):
        q = self.request.GET.get('q', '')
        queryset = self.model.objects.all()
        if q:
            queryset = queryset.filter(
                Q(group__name__icontains=q) |
                Q(module__name__icontains=q)
            )
        return queryset.order_by('group__name', 'module__name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('security:groupmodulepermission_create')
        return context

class GroupModulePermissionCreateView(PermissionMixin, CreateViewMixin, CreateView):
    model = GroupModulePermission
    form_class = GroupModulePermissionForm
    template_name = 'security/groupmodulepermission/form.html'
    success_url = reverse_lazy('security:groupmodulepermission_list')
    permission_required = 'add_groupmodulepermission'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = context['form']

        context['selected_permissions'] = list(form.initial.get('permissions', []).values_list('id', flat=True)) if form.initial.get('permissions') else []

        # Pasar permisos por módulo (para JS)
        modules = form.fields['module'].queryset
        module_permissions = {}
        for module in modules:
            perms = list(module.permissions.values('id', 'name'))
            module_permissions[str(module.id)] = perms
        context['module_permissions_json'] = module_permissions

        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        obj = self.object
        obj.permissions.set(form.cleaned_data['permissions'])
        messages.success(self.request, f"Permisos asignados correctamente al grupo {obj.group.name} sobre el módulo {obj.module.name}.")
        return response

class GroupModulePermissionUpdateView(PermissionMixin, UpdateViewMixin, UpdateView):
    model = GroupModulePermission
    form_class = GroupModulePermissionForm
    template_name = 'security/groupmodulepermission/form.html'
    success_url = reverse_lazy('security:groupmodulepermission_list')
    permission_required = 'change_groupmodulepermission'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = context['form']

        context['selected_permissions'] = list(self.object.permissions.values_list('id', flat=True)) if self.object.permissions.exists() else []

        modules = form.fields['module'].queryset
        module_permissions = {}
        for module in modules:
            perms = list(module.permissions.values('id', 'name'))
            module_permissions[str(module.id)] = perms
        context['module_permissions_json'] = module_permissions

        context['grabar'] = 'Actualizar Permisos por Grupo y Módulo'
        context['back_url'] = self.success_url

        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        self.object.permissions.set(form.cleaned_data['permissions'])
        messages.success(self.request, f"Permisos para grupo '{self.object.group.name}' y módulo '{self.object.module.name}' actualizados con éxito.")
        return response

class GroupModulePermissionDeleteView(PermissionMixin, DeleteViewMixin, DeleteView):
    model = GroupModulePermission
    template_name = 'core/delete.html'
    success_url = reverse_lazy('security:groupmodulepermission_list')
    permission_required = 'delete_groupmodulepermission'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['grabar'] = 'Eliminar Permisos por Grupo y Módulo'
        context['description'] = f"¿Desea eliminar los permisos para el grupo '{self.object.group.name}' y el módulo '{self.object.module.name}'?"
        context['back_url'] = self.success_url
        return context

    def form_valid(self, form):
        group = self.object.group.name
        module = self.object.module.name
        response = super().form_valid(form)
        messages.success(self.request, f"Permisos para grupo '{group}' y módulo '{module}' eliminados con éxito.")
        return response

applications/security/views/home.py
from django.views.generic import TemplateView
from applications.security.components.menu_module import MenuModule
from applications.security.components.mixin_crud import PermissionMixin

class ModuloTemplateView(PermissionMixin,TemplateView):
    template_name = 'home.html'
   
    def get_context_data(self, **kwargs):
        #context = super().get_context_data(**kwargs)
        context={}
        context["title"]= "IC - Modulos"
        context["title1"]= "Modulos Disponibles"
        MenuModule(self.request).fill(context)
        
        print("estoy saliendo en el modulo template view")
       
        return context

applications/security/views/menu.py
from django.contrib import messages
from django.urls import reverse_lazy
from applications.security.components.mixin_crud import CreateViewMixin, DeleteViewMixin, ListViewMixin, PermissionMixin, UpdateViewMixin
from applications.security.forms.menu import MenuForm
from applications.security.forms.module import ModuleForm
from applications.security.models import Menu, Module
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.db.models import Q


class MenuListView(PermissionMixin, ListViewMixin, ListView):
    template_name = 'security/menus/list.html'
    model = Menu
    context_object_name = 'menus'
    permission_required = 'view_menu'

    def get_queryset(self):
        q1 = self.request.GET.get('q')
        if q1 is not None:
            self.query.add(Q(name__icontains=q1), Q.OR)
           
        return self.model.objects.filter(self.query).order_by('id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('security:menu_create')
        print(context['permissions'])
        return context


class MenuCreateView(PermissionMixin, CreateViewMixin, CreateView):
    model = Menu
    template_name = 'security/menus/form.html'
    form_class = MenuForm
    success_url = reverse_lazy('security:menu_list')
    permission_required = 'add_menu'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['grabar'] = 'Grabar Menu'
        context['back_url'] = self.success_url
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        menu = self.object
        messages.success(self.request, f"Éxito al crear el menu {menu.name}.")
        return response


class MenuUpdateView(PermissionMixin, UpdateViewMixin, UpdateView):
    model = Menu
    template_name = 'security/menus/form.html'
    form_class = MenuForm
    success_url = reverse_lazy('security:menu_list')
    permission_required = 'change_menu'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['grabar'] = 'Actualizar Menu'
        context['back_url'] = self.success_url
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        menu = self.object
        messages.success(self.request, f"Éxito al actualizar el menu {menu.name}.")
        return response


class MenuDeleteView(PermissionMixin, DeleteViewMixin, DeleteView):
    model = Menu
    template_name = 'core/delete.html'
    success_url = reverse_lazy('security:menu_list')
    permission_required = 'delete_menu'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['grabar'] = 'Eliminar Menu'
        context['description'] = f"¿Desea eliminar el menu: {self.object.name}?"
        context['back_url'] = self.success_url
        return context

    
    def form_valid(self, form):
        # Guardar info antes de eliminar
        menu_name = self.object.name
        
        # Llamar al delete del padre
        response = super().form_valid(form)
        
        # Agregar mensaje
        messages.success(self.request, f"Éxito al eliminar lógicamente el menu {menu_name}.")
        
        return response

templates/security/users/list.html
{% extends 'home.html' %} 
<title>{% block title %}{{title}}{% endblock %}</title>
{% block content %}
    {% load static %}
    {% include 'fragments/messages.html' %}
    <section class="dark:bg-principal mt-2">
        <div class="text-center" data-aos="fade-up" data-aos-delay="200">
            <div class="sm:pt-8 lg:pt-4">
                
                    <h1 class="rounded-2xl  bg-indigo-500 px-2 py-1 text-white uppercase text-4xl">
                        {{ title1 }}
                    </h1>
               
            
               
            </div>
            <div class="lg:p-2 rounded-3xl" data-aos="fade-up" data-aos-delay="200">
                <!-- Barra de búsqueda -->
                <div class="p-4 flex justify-center">
                    <label for="table-search" class="sr-only">Search</label>
                    <div class="relative mt-1">
                        <div
                            class="absolute inset-y-0 rtl:inset-r-0 start-0 flex items-center ps-3 pointer-events-none">
                            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true"
                                xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                    stroke-width="2"
                                    d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
                            </svg>
                        </div>
                        <form method="GET" >
                            <input type="text" name="q" id="table-search"
                                class="text-center pl-10 shadow-sm bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 pr-12 dark:bg-principal dark:border-gray-600 dark:placeholder-gray-400 dark:text-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light"
                                placeholder="Búsqueda sin límites" value="{{ request.GET.q }}">
                        </form>
                    </div>
                </div>
                <!-- Tabla de usuarios -->
                <div class="overflow-x-auto">
                    <table class="w-full text-center text-lg">
                        <thead class="uppercase font-Tiny5 bg-gray-50 dark:bg-secundario dark:text-blue-300">
                            <tr>
                                <th scope="col" class="px-6 py-3">Nombre de usuario</th>
                                <th scope="col" class="px-6 py-3">DNI</th>
                                <th scope="col" class="px-6 py-3">Imagen</th>
                                <th scope="col" class="px-6 py-3">Email</th>
                                <th scope="col" class="px-6 py-3">Direction</th>
                                <th scope="col" class="px-6 py-3">Phone</th>
                                <th scope="col" class="px-6 py-3">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in users %}
                            <tr class="dark:text-gray-400 bg-white border-b dark:bg-[#0b1121] dark:border-secundario hover:bg-gray-50 dark:hover:bg-[#121c33]">
                                <td class="px-6 py-4">{{ item.username }}</td>
                                <td class="px-6 py-4">{{ item.dni }}</td>
                                <td class="px-6 py-4">
                                    <i class="{{ item.image }} text-2xl text-blue-600 dark:text-blue-400"></i>
                                </td>
                                <td class="px-6 py-4 font-semibold">{{ item.email }}</td>
                               
                                <td class="px-6 py-4">
                                    <span class="bg-gray-100 dark:bg-gray-800 px-2 py-1 rounded-full text-sm">
                                        {{ item.direction }}
                                    </span>
                                </td>
                                <td class="px-6 py-4 font-semibold">{{ item.phone }}</td>    
                               
                                <td class="px-6 py-4">
                                  {% if permissions.change_user %}
                                    <a href="{% url 'security:user_update' item.id %}"
                                        class="text-blue-600 dark:text-blue-500 hover:text-blue-800 mx-1">
                                        <i class="fa-solid fa-edit text-lg"></i>
                                    </a>
                                  {% endif%}  
                                  {% if permissions.delete_user %}
                                    <a href="#"
                                        class="text-red-600 dark:text-red-500 hover:text-red-800 mx-1"
                                        onclick="openDeleteModal('{{ item.id }}', '{{ item.name }}')">
                                        <i class="fa-solid fa-trash text-lg"></i>
                                    </a>
                                  {% endif %} 
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <!-- Paginación -->
                <div class="flex justify-center mt-4">
                    <nav aria-label="Page navigation example">
                        <ul class="inline-flex -space-x-px">
                            {% if page_obj.has_previous %}
                            <li>
                                <a href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                                    class="flex items-center justify-center px-3 h-8 ms-0 leading-tight text-gray-500 bg-white border border-e-0 border-gray-300 rounded-s-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-[#0b1121] dark:border-secundario dark:text-gray-400 dark:hover:bg-[#121c33] dark:hover:text-white">Anterior</a>
                            </li>
                            {% endif %}
                            {% for num in page_obj.paginator.page_range %}
                            <li>
                                <a href="?page={{ num }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                                    class="flex items-center justify-center px-3 h-8 leading-tight {% if num == page_obj.number %}text-blue-600 bg-blue-50 border border-gray-300 hover:bg-blue-100 hover:text-blue-700 dark:bg-secundario dark:border-principal dark:text-blue-300{% else %}text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-[#0b1121] dark:border-secundario dark:text-gray-400 dark:hover:bg-[#121c33] dark:hover:text-white{% endif %}">
                                    {{ num }}
                                </a>
                            </li>
                            {% endfor %}
                            {% if page_obj.has_next %}
                            <li>
                                <a href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                                    class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 rounded-e-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-[#0b1121] dark:border-secundario dark:text-gray-400 dark:hover:bg-[#121c33] dark:hover:text-white">Siguiente</a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>

                <!-- Enlaces adicionales -->
                <div class="flex flex-col md:flex-row justify-center form-group text-center p-4">
                    {% if permissions.add_user %}
                    <a class="bg-blue-700 hover:bg-blue-800 text-white py-2 px-4 rounded-full mr-0 md:mr-2 mb-2 md:mb-0 flex items-center justify-center transition-colors duration-300"
                        href="{% url 'security:user_create' %}">
                        <i class="fa-solid fa-plus mr-2"></i> Nuevo Usuario
                    </a>
                    {% endif %}
                    <a class="bg-blue-700 hover:bg-blue-800 text-white py-2 px-4 rounded-full flex items-center justify-center transition-colors duration-300"
                        href="{% url 'home' %}">
                        <i class="fa-solid fa-house"></i>
                    </a>
                </div>
            </div>
        </div>
    </section>

    {% include 'fragments/delete.html' %}
   <script>
function openDeleteModal(id, name) {
    const deleteForm = document.getElementById('deleteForm');
    deleteForm.action = `{% url 'security:user_delete' 0 %}`.replace('0', id);
    document.getElementById('Description').textContent = `ID: ${id} - ${name}`;
    document.getElementById('deleteModal').classList.remove('hidden');
}

function closeModal() {
    document.getElementById('deleteModal').classList.add('hidden');
}

// ✅ AGREGAR: Asegurar redirección correcta
document.addEventListener('DOMContentLoaded', function() {
    const deleteForm = document.getElementById('deleteForm');
    
    if (deleteForm) {
        deleteForm.addEventListener('submit', function(e) {
            // Opcional: Mostrar loading
            const submitBtn = deleteForm.querySelector('button[type="submit"]');
            if (submitBtn) {
                submitBtn.innerHTML = '<i class="fa-solid fa-spinner fa-spin"></i> Eliminando...';
                submitBtn.disabled = true;
            }
            
            // Permitir envío normal del formulario
            // Django manejará la redirección automáticamente
        });
    }
});
</script>
{% endblock %}